"""Add Traffic model

Revision ID: 34058071b9cd
Revises: 
Create Date: 2025-11-20 10:51:51.749098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34058071b9cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interface', sa.String(length=64), nullable=False),
    sa.Column('bytes_sent', sa.Integer(), nullable=False),
    sa.Column('bytes_recv', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic')
    # ### end Alembic commands ###
